//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.TimeSpan Until { get; set; }
        public bool Food_And_Drinks { get; set; }
        public bool Apply_For_Party { get; set; }
        public string Leave_Message { get; set; }
        public Nullable<int> Rate { get; set; }
        public string CustomerId { get; set; }
        public int KaraokeId { get; set; }
    
        public virtual Karaoke Karaoke { get; set; }
    }
}
