//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Location
    {
        public int Id { get; set; }
        [DisplayFormat(DataFormatString = "{0:###.########}")]
        public decimal Latitude { get; set; }
        [DisplayFormat(DataFormatString = "{0:###.########}")]
        public decimal Longitude { get; set; }
        public int KaraokeId { get; set; }
    
        public virtual Karaoke Karaoke { get; set; }
    }
}
